paths:
  metadata_csv: '/home/coder/project/covidxct/proc_slices_metadata.csv'
  autoencoder_path: 'models/generator/autoencoder/finetuned_autoencoder.pth'
  generator_path: "models/generator/generator/final_finetuned_generator.pth"
  imgs_output: "data/results/experiment_final/syn_data"
  result_csv: 'data/results/experiment_final/syn_data.csv'

num_inference_steps: 100
guidance_scale: 7
scale_factor: 0.9578254818916321

sample_size: 1000

conditioning:       # use null for no filter
  split: "test"      # val, ground_truth, test, train
  sex: null         # F or M
  age_group: null   # Under 20, 20-40, 40-60, 60-80, Over-80
  label: null       # 0 or 1