paths:
  metadata_csv: '/home/vito/fortunom/projects/AI4Health/data/fortunom/covidxct/proc_slices_metadata.csv'
  autoencoder_path: 'models/generator/autoencoder/finetuned_autoencoder.pth'
  generator_path: "models/generator/generator/finetuned_generator.pth"
  imgs_output: "data/results/experiment/syn_data"
  result_csv: 'data/results/experiment/syn_data.csv'

num_inference_steps: 50
guidance_scale: 7
scale_factor: 0.96109539270401
img_size: 256

sample_size: 10

conditioning:       # use null for no filter
  split: "val"      # val, ground_truth, test, train
  sex: null         # F or M
  age_group: null   # Under 20, 20-40, 40-60, 60-80, Over-80
  label: null       # 0 or 1