paths:
  metadata_csv: "/home/coder/project/covidxct/proc_slices_metadata.csv"
  autoencoder_model: "models/generator/autoencoder/autoencoder.pth"
  model_output: "models/generator"

columns:
  label: "label"
  attribute_cols: ["sex", "age_group"]
  image_path: "image_path"
  split_col: "split"

training:
  emb_size: 128
  batch_size: 128
  num_epochs: 200
  val_interval: 20
  guidance_scale: 7.0
