paths:
  metadata_csv: "/home/coder/project/covidxct/proc_slices_metadata.csv"
  autoencoder_path: 'models/generator/autoencoder/finetuned_autoencoder.pth'
  generator_path: "models/generator/generator/finetuned_generator.pth"
  scale_factor: 'models/generator/generator/scale.pt'
  imgs_output: "data/results/experiment/syn_data"
  result_csv: 'data/results/experiment/syn_data.csv'

num_inference_steps: 200
guidance_scale: 7
scale_factor: 0.96109539270401

conditioning:
  split: "val"
  sex: None
  age_group: None
  label: None