paths:
  real_imgs_csv: '/home/vito/fortunom/projects/AI4Health/data/fortunom/covidxct/proc_slices_metadata.csv'
  syn_1_path: 'data/syn_test/gen_1.csv'
  syn_2_path: 'data/syn_test/gen_2.csv'
  syn_3_path: 'data/syn_test/gen_3.csv'
  syn_4_path: 'data/syn_test/gen_4.csv'
  syn_5_path: 'data/syn_test/gen_5.csv'

columns:
  real_img_path: "image_path"
  syn_img_path: "syn_path"

target:
  attribute_columns: ["sex"]  # ["sex"] or ["age_group"] or ["label"] (diagnosis), or ["sex", "age_group"] etc.
  normalize_target: True  # whether to encode string target to integers

training:
  num_epochs: 20
  batch_size: 128
  learning_rate: 0.001
  val_interval: 1

split:
  train_size: 0.9
  val_size: 0.1
  stratify: True

output:
  results_dir: "results/conditioning_eval"