paths:
  real_imgs_csv: '/home/coder/project/covidxct/proc_slices_metadata.csv'
  syn_1_path: 'data/syn_test/gen_1.csv'
  syn_2_path: 'data/syn_test/gen_2.csv'
  syn_3_path: 'data/syn_test/gen_3.csv'
  syn_4_path: 'data/syn_test/gen_4.csv'
  syn_5_path: 'data/syn_test/gen_5.csv'

columns:
  real_img_path: "image_path"
  syn_img_path: "syn_path"
  target: "label"
  split_col: "split"

num_trains: 5

training:
  num_epochs: 20
  batch_size: 128
  learning_rate: 0.001
  val_interval: 1

split:
  train_size: 0.9
  val_size: 0.1

output:
  results_dir: "results/utility_train"
  real_model_output: "models/utility_train"
  syn_model_output_1: "models/utility_train/classifier_trained_syn_1.pth"
  syn_model_output_2: "models/utility_train/classifier_trained_syn_2.pth"
  syn_model_output_3: "models/utility_train/classifier_trained_syn_3.pth"
  syn_model_output_4: "models/utility_train/classifier_trained_syn_4.pth"
  syn_model_output_5: "models/utility_train/classifier_trained_syn_5.pth"