paths:
  metadata: "data/metadata.csv"
  nifti_root: "data/preprocessed_nifti"
  best_model_output: "models/classifier/best_tuned_model.pth"
  best_config_output: "config/classifier/results_tuned_model.yaml"

columns:
  patient_id: "Patient ID"
  diagnosis: "binary_diagnosis_patient"

param_grid:
  resize:
    - [64, 64, 64]
    - [96, 96, 96]
    - [128, 128, 128]
  rotation_prob:
    - 0.0
    - 0.5
    - 0.8
  batch_size:
    - 2
    - 4
  learning_rate:
    - 0.001
    - 0.0001
  num_workers:
    - 0
    - 2
  num_epochs:
    - 10
    - 20
    - 40
