DEBUG: False

paths:
  metadata_csv: "/home/coder/project/covidxct/proc_slices_metadata.csv"
  model_output: models/classifier/covid_densenet_model.pth

columns:
  label: "label"
  image_path: "image_path"
  split_col: "split"

training:
  early_stopping_patience: 5
  num_epochs: 20
  batch_size: 64
  learning_rate: 0.001
  val_interval: 1

